package com.example.demo.dto.ocpp.schema.notify_settlement_response;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.*;
import com.example.demo.model.ocpp.schema.enums.*;

@Data
@NoArgsConstructor
public class NotifySettlementResponse {


    @Size(max = 2000)
    /** The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver. */
    @JsonProperty("receiptUrl")
    private String receiptUrl;


    @Size(max = 50)
    /** The receipt id if the receipt is generated by CSMS. */
    @JsonProperty("receiptId")
    private String receiptId;


    @JsonProperty("customData")
    private CustomData customData;

}
