package com.example.demo.model.ocpp.schema.notify_settlement_request;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.*;
import com.example.demo.model.ocpp.schema.enums.*;

@Data
@NoArgsConstructor
@Entity
@Table(name = "notify_settlement_request")
public class NotifySettlementRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long schemaId;


    @Size(max = 36)
    /** The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction. */
    @Column(name = "transaction_id")
    private String transactionId;


    @Size(max = 255)
    /** The payment reference received from the payment terminal and is used as the value for _idToken_. */
    @Column(name = "psp_ref")
    private String pspRef;


    @Column(name = "status")
    private PaymentStatusEnum status;


    @Size(max = 500)
    /** Additional information from payment terminal/payment process. */
    @Column(name = "status_info")
    private String statusInfo;


    /** The amount that was settled, or attempted to be settled (in case of failure). */
    @Column(name = "settlement_amount")
    private Double settlementAmount;


    /** The time when the settlement was done. */
    @Column(name = "settlement_time")
    private String settlementTime;


    @Size(max = 50)
    @Column(name = "receipt_id")
    private String receiptId;


    @Size(max = 2000)
    /** The receipt URL, to be used if the receipt is generated by the payment terminal or the CS. */
    @Column(name = "receipt_url")
    private String receiptUrl;


    @Column(name = "vat_company")
    private Address vatCompany;


    @Size(max = 20)
    /** VAT number for a company receipt. */
    @Column(name = "vat_number")
    private String vatNumber;


    @Column(name = "custom_data")
    private CustomData customData;

}
