package com.example.demo.dto.ocpp.schema.notify_settlement_request;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.*;
import com.example.demo.model.ocpp.schema.enums.*;

@Data
@NoArgsConstructor
public class NotifySettlementRequest {


    @Size(max = 36)
    /** The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction. */
    @JsonProperty("transactionId")
    private String transactionId;


    @Size(max = 255)
    /** The payment reference received from the payment terminal and is used as the value for _idToken_. */
    @JsonProperty("pspRef")
    private String pspRef;


    @JsonProperty("status")
    private PaymentStatusEnum status;


    @Size(max = 500)
    /** Additional information from payment terminal/payment process. */
    @JsonProperty("statusInfo")
    private String statusInfo;


    /** The amount that was settled, or attempted to be settled (in case of failure). */
    @JsonProperty("settlementAmount")
    private Double settlementAmount;


    /** The time when the settlement was done. */
    @JsonProperty("settlementTime")
    private String settlementTime;


    @Size(max = 50)
    @JsonProperty("receiptId")
    private String receiptId;


    @Size(max = 2000)
    /** The receipt URL, to be used if the receipt is generated by the payment terminal or the CS. */
    @JsonProperty("receiptUrl")
    private String receiptUrl;


    @JsonProperty("vatCompany")
    private Address vatCompany;


    @Size(max = 20)
    /** VAT number for a company receipt. */
    @JsonProperty("vatNumber")
    private String vatNumber;


    @JsonProperty("customData")
    private CustomData customData;

}
