package com.example.demo.model.ocpp.schema.notify_settlement_response;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.*;
import com.example.demo.model.ocpp.schema.enums.*;

@Data
@NoArgsConstructor
@Entity
@Table(name = "notify_settlement_response")
public class NotifySettlementResponse {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long schemaId;


    @Size(max = 2000)
    /** The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver. */
    @Column(name = "receipt_url")
    private String receiptUrl;


    @Size(max = 50)
    /** The receipt id if the receipt is generated by CSMS. */
    @Column(name = "receipt_id")
    private String receiptId;


    @Column(name = "custom_data")
    private CustomData customData;

}
