package com.example.demo.model.ocpp.schema.enums;

public enum FirmwareStatusEnum {
    DOWNLOADED,
    DOWNLOADFAILED,
    DOWNLOADING,
    DOWNLOADSCHEDULED,
    DOWNLOADPAUSED,
    IDLE,
    INSTALLATIONFAILED,
    INSTALLING,
    INSTALLED,
    INSTALLREBOOTING,
    INSTALLSCHEDULED,
    INSTALLVERIFICATIONFAILED,
    INVALIDSIGNATURE,
    SIGNATUREVERIFIED,
}
