package com.example.demo.model.ocpp.schema.enums;

public enum IslandingDetectionEnum {
    NOANTIISLANDINGSUPPORT,
    ROCOF,
    UVP_OVP,
    UFP_OFP,
    VOLTAGEVECTORSHIFT,
    ZEROCROSSINGDETECTION,
    OTHERPASSIVE,
    IMPEDANCEMEASUREMENT,
    IMPEDANCEATFREQUENCY,
    SLIPMODEFREQUENCYSHIFT,
    SANDIAFREQUENCYSHIFT,
    SANDIAVOLTAGESHIFT,
    FREQUENCYJUMP,
    RCLQFACTOR,
    OTHERACTIVE,
}
