package com.example.demo.model.ocpp.schema.enums;

public enum MessageTriggerEnum {
    BOOTNOTIFICATION,
    LOGSTATUSNOTIFICATION,
    FIRMWARESTATUSNOTIFICATION,
    HEARTBEAT,
    METERVALUES,
    SIGNCHARGINGSTATIONCERTIFICATE,
    SIGNV2GCERTIFICATE,
    SIGNV2G20CERTIFICATE,
    STATUSNOTIFICATION,
    TRANSACTIONEVENT,
    SIGNCOMBINEDCERTIFICATE,
    PUBLISHFIRMWARESTATUSNOTIFICATION,
    CUSTOMTRIGGER,
}
