package com.example.demo.model.ocpp.schema.enums;

public enum ReasonEnum {
    DEAUTHORIZED,
    EMERGENCYSTOP,
    ENERGYLIMITREACHED,
    EVDISCONNECTED,
    GROUNDFAULT,
    IMMEDIATERESET,
    MASTERPASS,
    LOCAL,
    LOCALOUTOFCREDIT,
    OTHER,
    OVERCURRENTFAULT,
    POWERLOSS,
    POWERQUALITY,
    REBOOT,
    REMOTE,
    SOCLIMITREACHED,
    STOPPEDBYEV,
    TIMELIMITREACHED,
    TIMEOUT,
    REQENERGYTRANSFERREJECTED,
}
